name: PR Approval Workflow
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Restore Nuget
        run: find . -name "*.csproj" -exec dotnet restore '{}' \;
      - name: Build Projects
        run: find . -name "*.csproj" -exec dotnet build '{}' \;
      - name: Run Unit Tests
        run: find tests/UnitTests -name "*.csproj" -exec dotnet test '{}' \;
      - name: Run Integration Tests
        run: find tests/IntegrationTests -name "*.csproj" -exec dotnet test '{}' \;
